version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/London
    reviewers:
      - wopian
    labels:
      - 'Type: Maintenance'
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/London
    allow:
      - dependency-type: direct
    reviewers:
      - wopian
    labels:
      - 'Type: Maintenance'
    open-pull-requests-limit: 1
